#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod erc20;
pub mod rmm01_portfolio;
pub mod weth;
pub mod shared_types;

// Testing
pub mod arbiter_token;
pub mod writer;