pub use unsafe_math_echidna_test::*;
/// This module was auto-generated with ethers-rs Abigen.
/// More information at: <https://github.com/gakonst/ethers-rs>
#[allow(
    clippy::enum_variant_names,
    clippy::too_many_arguments,
    clippy::upper_case_acronyms,
    clippy::type_complexity,
    dead_code,
    non_camel_case_types
)]
pub mod unsafe_math_echidna_test {
    #[rustfmt::skip]
    const __ABI: &str = "[{\"inputs\":[{\"internalType\":\"uint256\",\"name\":\"x\",\"type\":\"uint256\",\"components\":[]},{\"internalType\":\"uint256\",\"name\":\"d\",\"type\":\"uint256\",\"components\":[]}],\"stateMutability\":\"pure\",\"type\":\"function\",\"name\":\"checkDivRoundingUp\",\"outputs\":[]}]";
    ///The parsed JSON ABI of the contract.
    pub static UNSAFEMATHECHIDNATEST_ABI: ::ethers::contract::Lazy<::ethers::core::abi::Abi> =
        ::ethers::contract::Lazy::new(|| {
            ::ethers::core::utils::__serde_json::from_str(__ABI).expect("ABI is always valid")
        });
    #[rustfmt::skip]
    const __BYTECODE: &[u8] = &[
        96,
        128,
        96,
        64,
        82,
        52,
        128,
        21,
        97,
        0,
        16,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        96,
        221,
        128,
        97,
        0,
        31,
        96,
        0,
        57,
        96,
        0,
        243,
        254,
        96,
        128,
        96,
        64,
        82,
        52,
        128,
        21,
        96,
        15,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        96,
        4,
        54,
        16,
        96,
        40,
        87,
        96,
        0,
        53,
        96,
        224,
        28,
        128,
        99,
        39,
        36,
        218,
        78,
        20,
        96,
        45,
        87,
        91,
        96,
        0,
        128,
        253,
        91,
        96,
        77,
        96,
        4,
        128,
        54,
        3,
        96,
        64,
        129,
        16,
        21,
        96,
        65,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        128,
        53,
        144,
        96,
        32,
        1,
        53,
        96,
        79,
        86,
        91,
        0,
        91,
        96,
        0,
        129,
        17,
        96,
        91,
        87,
        96,
        0,
        128,
        253,
        91,
        96,
        0,
        96,
        101,
        131,
        131,
        96,
        156,
        86,
        91,
        144,
        80,
        96,
        0,
        130,
        132,
        129,
        96,
        113,
        87,
        254,
        91,
        4,
        130,
        3,
        144,
        80,
        130,
        132,
        129,
        96,
        126,
        87,
        254,
        91,
        6,
        96,
        141,
        87,
        128,
        21,
        96,
        137,
        87,
        254,
        91,
        96,
        150,
        86,
        91,
        128,
        96,
        1,
        20,
        96,
        150,
        87,
        254,
        91,
        80,
        80,
        80,
        80,
        86,
        91,
        128,
        130,
        4,
        145,
        6,
        21,
        21,
        1,
        144,
        86,
        254,
        162,
        100,
        105,
        112,
        102,
        115,
        88,
        34,
        18,
        32,
        80,
        109,
        90,
        148,
        229,
        94,
        39,
        189,
        117,
        191,
        26,
        238,
        87,
        1,
        186,
        124,
        63,
        53,
        41,
        193,
        97,
        151,
        76,
        93,
        23,
        138,
        141,
        141,
        136,
        197,
        92,
        201,
        100,
        115,
        111,
        108,
        99,
        67,
        0,
        7,
        6,
        0,
        51,
    ];
    ///The bytecode of the contract.
    pub static UNSAFEMATHECHIDNATEST_BYTECODE: ::ethers::core::types::Bytes =
        ::ethers::core::types::Bytes::from_static(__BYTECODE);
    #[rustfmt::skip]
    const __DEPLOYED_BYTECODE: &[u8] = &[
        96,
        128,
        96,
        64,
        82,
        52,
        128,
        21,
        96,
        15,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        96,
        4,
        54,
        16,
        96,
        40,
        87,
        96,
        0,
        53,
        96,
        224,
        28,
        128,
        99,
        39,
        36,
        218,
        78,
        20,
        96,
        45,
        87,
        91,
        96,
        0,
        128,
        253,
        91,
        96,
        77,
        96,
        4,
        128,
        54,
        3,
        96,
        64,
        129,
        16,
        21,
        96,
        65,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        128,
        53,
        144,
        96,
        32,
        1,
        53,
        96,
        79,
        86,
        91,
        0,
        91,
        96,
        0,
        129,
        17,
        96,
        91,
        87,
        96,
        0,
        128,
        253,
        91,
        96,
        0,
        96,
        101,
        131,
        131,
        96,
        156,
        86,
        91,
        144,
        80,
        96,
        0,
        130,
        132,
        129,
        96,
        113,
        87,
        254,
        91,
        4,
        130,
        3,
        144,
        80,
        130,
        132,
        129,
        96,
        126,
        87,
        254,
        91,
        6,
        96,
        141,
        87,
        128,
        21,
        96,
        137,
        87,
        254,
        91,
        96,
        150,
        86,
        91,
        128,
        96,
        1,
        20,
        96,
        150,
        87,
        254,
        91,
        80,
        80,
        80,
        80,
        86,
        91,
        128,
        130,
        4,
        145,
        6,
        21,
        21,
        1,
        144,
        86,
        254,
        162,
        100,
        105,
        112,
        102,
        115,
        88,
        34,
        18,
        32,
        80,
        109,
        90,
        148,
        229,
        94,
        39,
        189,
        117,
        191,
        26,
        238,
        87,
        1,
        186,
        124,
        63,
        53,
        41,
        193,
        97,
        151,
        76,
        93,
        23,
        138,
        141,
        141,
        136,
        197,
        92,
        201,
        100,
        115,
        111,
        108,
        99,
        67,
        0,
        7,
        6,
        0,
        51,
    ];
    ///The deployed bytecode of the contract.
    pub static UNSAFEMATHECHIDNATEST_DEPLOYED_BYTECODE: ::ethers::core::types::Bytes =
        ::ethers::core::types::Bytes::from_static(__DEPLOYED_BYTECODE);
    pub struct UnsafeMathEchidnaTest<M>(::ethers::contract::Contract<M>);
    impl<M> ::core::clone::Clone for UnsafeMathEchidnaTest<M> {
        fn clone(&self) -> Self {
            Self(::core::clone::Clone::clone(&self.0))
        }
    }
    impl<M> ::core::ops::Deref for UnsafeMathEchidnaTest<M> {
        type Target = ::ethers::contract::Contract<M>;
        fn deref(&self) -> &Self::Target {
            &self.0
        }
    }
    impl<M> ::core::ops::DerefMut for UnsafeMathEchidnaTest<M> {
        fn deref_mut(&mut self) -> &mut Self::Target {
            &mut self.0
        }
    }
    impl<M> ::core::fmt::Debug for UnsafeMathEchidnaTest<M> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_tuple(stringify!(UnsafeMathEchidnaTest))
                .field(&self.address())
                .finish()
        }
    }
    impl<M: ::ethers::providers::Middleware> UnsafeMathEchidnaTest<M> {
        /// Creates a new contract instance with the specified `ethers` client at
        /// `address`. The contract derefs to a `ethers::Contract` object.
        pub fn new<T: Into<::ethers::core::types::Address>>(
            address: T,
            client: ::std::sync::Arc<M>,
        ) -> Self {
            Self(::ethers::contract::Contract::new(
                address.into(),
                UNSAFEMATHECHIDNATEST_ABI.clone(),
                client,
            ))
        }
        /// Constructs the general purpose `Deployer` instance based on the provided constructor arguments and sends it.
        /// Returns a new instance of a deployer that returns an instance of this contract after sending the transaction
        ///
        /// Notes:
        /// - If there are no constructor arguments, you should pass `()` as the argument.
        /// - The default poll duration is 7 seconds.
        /// - The default number of confirmations is 1 block.
        ///
        ///
        /// # Example
        ///
        /// Generate contract bindings with `abigen!` and deploy a new contract instance.
        ///
        /// *Note*: this requires a `bytecode` and `abi` object in the `greeter.json` artifact.
        ///
        /// ```ignore
        /// # async fn deploy<M: ethers::providers::Middleware>(client: ::std::sync::Arc<M>) {
        ///     abigen!(Greeter, "../greeter.json");
        ///
        ///    let greeter_contract = Greeter::deploy(client, "Hello world!".to_string()).unwrap().send().await.unwrap();
        ///    let msg = greeter_contract.greet().call().await.unwrap();
        /// # }
        /// ```
        pub fn deploy<T: ::ethers::core::abi::Tokenize>(
            client: ::std::sync::Arc<M>,
            constructor_args: T,
        ) -> ::core::result::Result<
            ::ethers::contract::builders::ContractDeployer<M, Self>,
            ::ethers::contract::ContractError<M>,
        > {
            let factory = ::ethers::contract::ContractFactory::new(
                UNSAFEMATHECHIDNATEST_ABI.clone(),
                UNSAFEMATHECHIDNATEST_BYTECODE.clone().into(),
                client,
            );
            let deployer = factory.deploy(constructor_args)?;
            let deployer = ::ethers::contract::ContractDeployer::new(deployer);
            Ok(deployer)
        }
        ///Calls the contract's `checkDivRoundingUp` (0x2724da4e) function
        pub fn check_div_rounding_up(
            &self,
            x: ::ethers::core::types::U256,
            d: ::ethers::core::types::U256,
        ) -> ::ethers::contract::builders::ContractCall<M, ()> {
            self.0
                .method_hash([39, 36, 218, 78], (x, d))
                .expect("method not found (this should never happen)")
        }
    }
    impl<M: ::ethers::providers::Middleware> From<::ethers::contract::Contract<M>>
        for UnsafeMathEchidnaTest<M>
    {
        fn from(contract: ::ethers::contract::Contract<M>) -> Self {
            Self::new(contract.address(), contract.client())
        }
    }
    ///Container type for all input parameters for the `checkDivRoundingUp` function with signature `checkDivRoundingUp(uint256,uint256)` and selector `0x2724da4e`
    #[derive(
        Clone,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
        Debug,
        PartialEq,
        Eq,
        Hash,
    )]
    #[ethcall(
        name = "checkDivRoundingUp",
        abi = "checkDivRoundingUp(uint256,uint256)"
    )]
    pub struct CheckDivRoundingUpCall {
        pub x: ::ethers::core::types::U256,
        pub d: ::ethers::core::types::U256,
    }
}
